workflows:
  ios-workflow:
    name: iOS workflow
    instance_type: mac_mini
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
